name: Build

# Worflow will run on pushes to all branhes + pull requests to all branches
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/build-push-action@v4
        with:
          push: false
          tags: simonjensen/docker-nginx:testing
